baseURL = "https://liangjun.work"
title = "Time Machine"
theme = "hugo-freedom"
copyright = "©2017-2020"

defaultContentLanguage = "zh-cn"
hasCJKLanguage = true
enableEmoji = true
buildFuture = true
enableRobotsTXT = true

[taxonomies]
tag = "tags"

[markup.highlight]
codeFences = true
noClasses = true
guessSyntax = true

[markup.goldmark.renderer]
unsafe = true

[params]
author = "wuzehui"
dateFormat = "2006-01-02"
slogan = "~人生苦短，何必太认真~"
ICP = "蒙ICP备18005213号"
icpUrl = "http://beian.miit.gov.cn"
description = "一个集技术、折腾、扯淡于一体的博客"
welcome = "欢迎来到我的时光机!"
license = "<a rel=\"license\" target=\"_blank\" href=\"http://creativecommons.org/licenses/by-nc-sa/4.0/\"><img alt=\"知识共享许可协议\" style=\"border-width:0;width:80px;\" src=\"https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png\"/></a><br>本博客文章均采用<a rel=\"license\" target=\"_blank\" href=\"http://creativecommons.org/licenses/by-nc-sa/4.0/\">知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议</a>进行许可"

[[params.nav.custom]]
title = "Posts"
url = "/posts"

[[params.nav.custom]]
title = "Tags"
# url必须为tags，对应默认生成的tags目录(当然代码里面也有部分硬编码)
url = "/tags"

[[params.nav.custom]]
title = "Github"
url = "https://github.com/wuzehv"

[[params.nav.custom]]
title = "Email"
url = "mailto://bugfixeng@gmail.com"

[[params.link.friends]]
pic = "https://blog.tangdongsheng.com/kid.jpg"
title = "夏木断弦"
url = "https://blog.tangdongsheng.com/"
slogan = "宠辱不惊,闲看庭前花开花落;去留无意,漫随天外云卷云舒"