baseURL = "https://liangjun.work"
title = "Time Machine"
theme = "hugo-freedom"
copyright = "©2017"

defaultContentLanguage = "zh-cn"
hasCJKLanguage = true
enableEmoji = true
buildFuture = true
enableRobotsTXT = true

[taxonomies]
tag = "tags"

[markup.goldmark.renderer]
unsafe = true
[markup]
[markup.tableOfContents]
endLevel = 5
ordered = false
startLevel = 2

# 配合prism来显示高亮
[markup.highlight]
codeFences = true
noClasses = true
guessSyntax = true

# 这里放自定义参数
[params]
author = "吴泽辉"
email = "bugfixeng@gmail.com"
dateFormat = "2006-01-02"
# 显示在左侧sidebar logo下面
logo = "/images/cat.jpeg"
slogan = "~人生苦短，何必太认真~"
welcome = "一个平平无奇的博客"

description = "一个包含技术、折腾和扯淡的网站"

# 备案号
ICP = "京ICP备2021036734号"
# 备案的网站title
icpTitle = ""
icpUrl = "http://beian.miit.gov.cn"

github = "https://github.com/wuzehv"

license = "本文章为原创，采用《<a class=\"text-secondary\" rel=\"license\" target=\"_blank\" href=\"http://creativecommons.org/licenses/by-nc-nd/4.0/\">知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议</a>》进行许可。"

# 最新文章展示条数
latestLen = 10

# 导航
[[params.nav.custom]]
title = "文章"
url = "/posts"

[[params.nav.custom]]
title = "标签"
# url必须为tags，对应默认生成的tags目录(当然代码里面也有部分硬编码)
url = "/tags"

# 友情链接
[[params.link.friends]]
title = "夏木断弦"
url = "https://blog.tangdongsheng.com/"
slogan = "宠辱不惊,闲看庭前花开花落;去留无意,漫随天外云卷云舒"

[[params.link.friends]]
title = "一包小浣熊里五张卡"
url = "https://zhangxi.site/"
slogan = "Live your life with passion! With some drive!"

# 标签描述
[[params.tag.show]]
title = "Nginx"
desc = "高性能web server"
[[params.tag.show]]
title = "Git"
desc = "分布式版本控制系统"
[[params.tag.show]]
title = "摄影"
desc = "用摄影来记录时光"
[[params.tag.show]]
title = "Emacs"
desc = "神的编辑器"
[[params.tag.show]]
title = "杂项"
desc = "穷折腾"
[[params.tag.show]]
title = "扯淡"
desc = "一本正经的胡说八道"
[[params.tag.show]]
title = "c语言"
desc = "短小精悍的编程语言"
[[params.tag.show]]
title = "Linux"
desc = "应用广泛的开源操作系统"
[[params.tag.show]]
title = "PHP"
desc = "不用多说，\"世界上最好的语言是也\""
[[params.tag.show]]
title = "MySQL"
desc = "使用最广泛的开源RDBMS"

# 资源文件
[module]
[[module.mounts]]
source = "assets"
target = "assets"
